### ISSUE TITLE
test case failure

### ISSUE THREAD

**Issue by pnemade** [floatdrop/duplexer2#1]
I am packaging nodejs-duplexer3 in Fedora and in %check section I am getting this

```
+ mocha -R tap
1..13
ok 1 duplexer3 should interact with the writable stream properly for writing
ok 2 duplexer3 should interact with the readable stream properly for reading
ok 3 duplexer3 should end the writable stream, causing it to finish
ok 4 duplexer3 should finish when the writable stream finishes
ok 5 duplexer3 should end when the readable stream ends
ok 6 duplexer3 should bubble errors from the writable stream when no behaviour is specified
ok 7 duplexer3 should bubble errors from the readable stream when no behaviour is specified
ok 8 duplexer3 should bubble errors from the writable stream when bubbleErrors is true
ok 9 duplexer3 should bubble errors from the readable stream when bubbleErrors is true
ok 10 duplexer3 should not bubble errors from the writable stream when bubbleErrors is false
ok 11 duplexer3 should not bubble errors from the readable stream when bubbleErrors is false
ok 12 duplexer3 should export the DuplexWrapper constructor
not ok 13 duplexer3 should not force flowing-mode
  AssertionError: false == null
      at Context.<anonymous> (/home/parag/rpmbuild/BUILD/duplexer3-0.1.4/test/tests.js:171:12)
      at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
      at /usr/lib/node_modules/mocha/lib/runner.js:271:7
      at done (/usr/lib/node_modules/mocha/lib/runnable.js:185:5)
      at callFn (/usr/lib/node_modules/mocha/lib/runnable.js:228:7)
      at Hook.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:216:7)
      at next (/usr/lib/node_modules/mocha/lib/runner.js:259:10)
      at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
# tests 13
# pass 12
# fail 1
error: Bad exit status from /var/tmp/rpm-tmp.6fsewS (%check)
```

Can you help to fix this?

**Comment by floatdrop** [comment]
@pnemade this test will fain on Node.JS <= 4 (because we removed `readable-stream` from module). I guess you using old Node.JS for packaging.

**Comment by pnemade** [comment]
Right. I am using nodejs-0.10.36 on Fedora 23 system. I installed nodejs-4.2.3 and it built successfully there.

Thank you for your quick help.
